### ISSUE TITLE
Monai library error

### ISSUE THREAD

**Issue by anjieyin** [davidiommi/SALMON---3D-Medical-Images-Segmentation#1]
First of all, thanks for the great library ! It has really accelerated my work being able to start with a nice implementation of 3D unets. But I encountered the following problems when running the code of version_1, do you have any good suggestions for me? Looking forward to your reply.
![image](https://user-images.githubusercontent.com/73421914/114298418-e9c4a180-9ae8-11eb-800d-d5f41512b453.png)

**Comment by davidiommi** [comment]
Can you share more screens? To me, it seems something is not working when you load the data for the network or there is a particular transformation in the augmentation process that creates a problem.

Did you try to run check_loader_patches and play around with the transformations? It should give you an idea if the loader to the network works.

**Comment by davidiommi** [comment]
Most probably is the wrong Monai version installed. They do update them periodically and there are compatibility issues. As I previously said, try to check which transforms is giving problems with checkloader_patches
