### ISSUE TITLE
I met this error when run using my dataset.

### ISSUE THREAD

**Issue by bemoregt** [davidiommi/SALMON---3D-Medical-Images-Segmentation#3]
Hi, @davidiommi 

I met this error when run using my dataset (T1 nii & segmentation nii files).

What's wrong to me?

"y should be a binarized tensor"

...

58/64, train_loss: -0.9193
59/64, train_loss: -0.8782
60/64, train_loss: -0.9552
61/64, train_loss: 0.0053
62/64, train_loss: -0.8565
63/64, train_loss: -0.9150
64/64, train_loss: -0.4811
epoch 1 average loss: -0.3757
Traceback (most recent call last):
  File "train.py", line 324, in <module>
    main()
  File "train.py", line 287, in main
    metric, val_images, val_labels, val_outputs = plot_dice(val_loader)
  File "train.py", line 280, in plot_dice
    value, _ = dice_metric(y_pred=val_outputs, y=val_labels)
  File "/root/anaconda3/lib/python3.8/site-packages/monai/metrics/metric.py", line 216, in __call__
    ret = super().__call__(y_pred=y_pred, y=y)
  File "/root/anaconda3/lib/python3.8/site-packages/monai/metrics/metric.py", line 66, in __call__
    ret = self._compute_tensor(y_pred.detach(), y_)
  File "/root/anaconda3/lib/python3.8/site-packages/monai/metrics/meandice.py", line 75, in _compute_tensor
    raise ValueError("y should be a binarized tensor.")
ValueError: y should be a binarized tensor.

Thanks in advance.

Best,

@bemoregt.

**Comment by davidiommi** [comment]
Hi, 
check your label data values: 

Either something is happening in TrainTransforms/ValTransforms to the label images and they are not binary anymore, or you are performing a binary segmentation but in your original dataset there are values that are not 0 or 1.

If you are doing a multilabel segmentation, there is the other example with the peripherical zone and main gland of the prostate, where you have 0,1,2 values of the labels.

Best.

**Comment by bemoregt** [comment]
Many Thanks @davidiommi .

I'll try your multi-label segmentation example. 

Thank you in advance ~

@bemoregt.

**Comment by bemoregt** [comment]
> Hi,
> check your label data values:
> 
> Either something is happening in TrainTransforms/ValTransforms to the label images and they are not binary anymore, or you are performing a binary segmentation but in your original dataset there are values that are not 0 or 1.
> 
> If you are doing a multilabel segmentation, there is the other example with the peripherical zone and main gland of the prostate, where you have 0,1,2 values of the labels.
> 
> Best.

number of GPU: 1
Number of training patches per epoch: 8
Number of training images per epoch: 8
Number of validation images per epoch: 2
Number of test images per epoch: 1
----------
epoch 1/200
/root/anaconda3/lib/python3.8/site-packages/monai/losses/dice.py:121: UserWarning: single channel prediction, `softmax=True` ignored.
  warnings.warn("single channel prediction, `softmax=True` ignored.")
/root/anaconda3/lib/python3.8/site-packages/monai/losses/dice.py:130: UserWarning: single channel prediction, `to_onehot_y=True` ignored.
  warnings.warn("single channel prediction, `to_onehot_y=True` ignored.")
1/8, train_loss: 0.8408
2/8, train_loss: -0.0953
3/8, train_loss: -1.4629
4/8, train_loss: -5.5523
5/8, train_loss: -7.6788
6/8, train_loss: -10.1960
7/8, train_loss: -16.0166
8/8, train_loss: -38.5599
epoch 1 average loss: -9.8401
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16230,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16230,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16230,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16530,0,0], thread: [35,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16236,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16236,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16236,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16236,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16236,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train.py", line 336, in <module>
    main()
  File "train.py", line 293, in main
    metric, val_images, val_labels, val_outputs = plot_dice(val_loader)
  File "train.py", line 286, in plot_dice
    value, _ = dice_metric(y_pred=val_outputs, y=val_labels)
  File "/root/anaconda3/lib/python3.8/site-packages/monai/metrics/metric.py", line 216, in __call__
    ret = super().__call__(y_pred=y_pred, y=y)
  File "/root/anaconda3/lib/python3.8/site-packages/monai/metrics/metric.py", line 66, in __call__
    ret = self._compute_tensor(y_pred.detach(), y_)
  File "/root/anaconda3/lib/python3.8/site-packages/monai/metrics/meandice.py", line 72, in _compute_tensor
    if not torch.all(y_pred.byte() == y_pred):
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16530,0,0], thread: [8,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16530,0,0], thread: [9,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [16530,0,0], thread: [13,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

What's wrong to me ?

Best,
@bemoregt.

**Comment by davidiommi** [comment]
Dear bemoregt.,

to me, it looks you are launching the code without reviewing your data values or format. 

Try first to check if your data are correct (values, binary/multilabel, correctly overlaid images/labels) with check_loader_patches.py to see which images are loaded. Use also 3D Slicer https://www.slicer.org/ to check your data.

Best.
